SELECT S.NAME FROM STUDENTS S
INNER JOIN FRIENDS F ON F.ID = S.ID
INNER JOIN PACKAGES P1 ON P1.ID = S.ID
INNER JOIN PACKAGES P2 ON P2.ID = F.FRIEND_ID
WHERE P2.SALARY > P1.SALARY
ORDER BY P2.SALARY ASC;
