SELECT H.HACKER_ID, H.NAME AS CONTA FROM HACKERS H
INNER JOIN SUBMISSIONS S ON S.HACKER_ID = H.HACKER_ID
INNER JOIN CHALLENGES C ON C.CHALLENGE_ID = S.CHALLENGE_ID
INNER JOIN DIFFICULTY D ON D.DIFFICULTY_LEVEL = C.DIFFICULTY_LEVEL
WHERE S.SCORE = D.SCORE
GROUP BY H.HACKER_ID, H.NAME
HAVING COUNT(C.CHALLENGE_ID) > 1
ORDER BY COUNT(C.CHALLENGE_ID) DESC, S.HACKER_ID ASC;
